### ISSUE TITLE
Automating IP in notes

### ISSUE THREAD

**Issue by cseftw** [samari-k/useful-scripts#1]
If you use obsidian for note taking then you can use **templater** plugin for automating IP in your notes , have a look at this video : https://www.youtube.com/watch?v=2NLi4wzAvTw&t=634s .

**Comment by samari-k** [comment]
Oh that's nice, I will have a look it, thanks :+1:

**Comment by cseftw** [comment]
Also another issue you might look into is tun0 script in repository ,  `echo -n $IP | xclip -selection -c` this will not copy ip to your clipboard . Fix it using ` echo -n $IP | xclip -selection c`

**Comment by samari-k** [comment]
Odd, how did I miss that? ^^ Thanks!
